//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TierGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TierGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;appSettings&gt;
        ///		&lt;add key=&quot;Main.ConnectionString&quot; value=&quot;$CONNECTION_STRING$&quot; /&gt;
        ///	&lt;/appSettings&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;$PROJECT_NAMESPACE$.BusinessLayer&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;iqbal&quot;)]
        ///[assembly: AssemblyProduct(&quot;$PROJECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// base class for all business objects
        ///    /// &lt;/summary&gt;
        ///    public abstract class BusinessObjectBase : INotifyPropertyChanged
        ///    {
        ///
        ///        #region Data Member
        ///
        ///        bool _disablePropertyChangeEvent = false;
        ///        Validation.ValidationRules _validationRules = null;
        ///
        ///        #endregion
        ///
        ///        #region Properties
        ///
        ///        #region Int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_BusinessObjectBase {
            get {
                return ResourceManager.GetString("Business_BusinessObjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Data;
        ///using $PROJECT_NAMESPACE$.BusinessLayer.DataLayer;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    public class $CLASS_NAME$Factory
        ///    {
        ///
        ///        #region data Members
        ///
        ///        $CLASS_NAME$Sql _dataObject = null;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        public $CLASS_NAME$Factory()
        ///        {
        ///            _dataObject = new $CLASS_NAME$Sql();
        ///        }
        ///
        ///        #endregion
        ///
        ///
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_BusinessObjectFactory {
            get {
                return ResourceManager.GetString("Business_BusinessObjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to create custom exception
        ///    /// &lt;/summary&gt;
        ///    public class InvalidBusinessObjectException: Exception
        ///    {
        ///
        ///        #region Data members
        ///
        ///        string _methodName = string.Empty;
        ///
        ///        #endregion 
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor to set message
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_InvalidBusinessObjectException {
            get {
                return ResourceManager.GetString("Business_InvalidBusinessObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{C6FD9F84-A18E-472D-BA4B-7ED274F5B276}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_ProdjectFile {
            get {
                return ResourceManager.GetString("Business_ProdjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Data.SqlTypes;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.DataLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Data layer base class for database interaction.
        ///    /// &lt;/summary&gt;
        ///    abstract class DataLayerBase : IDisposable
        ///    {
        ///        #region Data Members
        ///
        ///        SqlConnection _mainConnection;        
        ///        bool _isDisposed;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;sum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataLayer_DataLayerBase {
            get {
                return ResourceManager.GetString("DataLayer_DataLayerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Data;
        ///using System.Data.SqlTypes;
        ///using System.Data.SqlClient;
        ///using System.Collections.Generic;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.DataLayer
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Data access layer class for $CLASS_NAME$
        ///	/// &lt;/summary&gt;
        ///	class $CLASS_NAME$Sql : DataLayerBase 
        ///	{
        ///
        ///        #region Constructor
        ///
        ///		/// &lt;summary&gt;
        ///		/// Class constructor
        ///		/// &lt;/summary&gt;
        ///		public $CLASS_NAME$Sql()
        ///		{
        ///			// Nothing for now.
        ///		}
        ///
        ///        #endregion
        ///
        ///        #region Pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataLayer_EntitySql {
            get {
                return ResourceManager.GetString("DataLayer_EntitySql", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DbInfo {
            get {
                object obj = ResourceManager.GetObject("DbInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Broken rules
        ///    /// &lt;/summary&gt;
        ///    public class BrokenRule
        ///    {
        ///
        ///        #region Data Members
        ///
        ///        string _ruleName = string.Empty;
        ///        string _description = string.Empty;
        ///        string _propertyName = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// constructor to get rule inf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_BrokenRule {
            get {
                return ResourceManager.GetString("Validation_BrokenRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to containt the list of the broken rules
        ///    /// &lt;/summary&gt;
        ///    public class BrokenRulesList : List&lt;BrokenRule&gt;
        ///    {
        ///        #region Internal Methods
        ///
        ///        /// &lt;summary&gt;
        ///        /// Add broken rule into the list
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;rule&quot;&gt;rule&lt;/param&gt;
        ///        internal void Add(ValidateRuleBase rule)
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_BrokenRulesList {
            get {
                return ResourceManager.GetString("Validation_BrokenRulesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Comparing for validation rules
        ///    /// &lt;/summary&gt;
        ///    public abstract class ValidateRuleBase
        ///    {
        ///        #region Data Members
        ///
        ///        string _propertyName = string.Empty;
        ///        string _friendlyName = string.Empty;
        ///        string _description = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleBase {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate Not null rule
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleNotNull : ValidateRuleBase
        ///    {
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;name of property&lt;/param&gt;
        ///        public ValidateRuleNotNull(string propertyName)
        ///            : this(propert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleNotNull {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate using Regular expression
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleRegexMatching : ValidateRuleBase
        ///    {
        ///        #region Data Members
        ///
        ///        string _regexExpression = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleRegexMatching {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleRegexMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate the maximun length of the string
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleStringMaxLength : ValidateRuleBase
        ///    {
        ///
        ///        #region Data member
        ///
        ///        int _length = 0;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constrcutor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleStringMaxLength {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Validate the required value
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleStringRequired : ValidateRuleBase
        ///    {
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;name of property&lt;/param&gt;
        ///        public ValidateRuleStringRequired(string propertyName)
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleStringRequired {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Reflection;
        ///
        ///namespace $PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to contain the validation rules of the object
        ///    /// &lt;/summary&gt;
        ///    class ValidationRules
        ///    {
        ///
        ///        #region Data Members
        ///
        ///        BrokenRulesList _brokenRulesList = null;
        ///        Dictionary&lt;string, List&lt;ValidateRuleBase&gt;&gt; _validationRulesList = null;
        ///        object _parentObject = null;
        ///
        ///        #endregi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidationRules {
            get {
                return ResourceManager.GetString("Validation_ValidationRules", resourceCulture);
            }
        }
    }
}
